##
# My subroutes

-
  name: 'Dancer'
  uriPattern: '<DancerSubroutes>'
  defaults:
    '@package': 'MyCompany.MyPackage'
    '@format':  'html'
  subRoutes:
    'DancerSubroutes':
      package: 'MyCompany.MyPackage'
