-
  name: 'dancer'
  uriPattern: '{locale}/{@controller}(/{@action})'
  defaults:
    'locale': 'en'
    '@controller': 'Dancer'
    '@action':     'index'
    '@format':     'html'
-
  name: 'about'
  uriPattern: '{locale}/about'
  defaults:
    'locale': 'en'
    '@controller': 'About'
    '@action':     'index'
    '@format':     'html'
