Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'languageDetection':
              position: 'after routing'
              component: 'MyCompany\MyPackage\Http\LanguageDetectionComponent'
    i18n:
      defaultLocale: en
